language: java

jdk:
  - openjdk8

addons:
  sonarcloud:
    organization: "fs7-final-project"
    token:
      secure: "k1RHHPlWmeR8DkeUS9sSVWN3LNoadWyQ13afl5UYF1IlOLhrrbrBaeakNXS65j7Zyoi3yhSFZFUfGDvnyl4Q3PASi0pCC91T7otvTgd1QLxfYXTJPpNakcLI1sR8hJEsuPa5Q3T3GNVzndFalCw8aUFQrvEw9NXhxK0ga14Wjcg0IzXVs+rTWTGZoozbL3dDzLl2gXDfCLLM4e+ovXd6qqf676JTEfLm22MUYVNFWD/8rHpje8WSsUMqS6BBpdqK11LA2nDhC/ZUc/J8IUpghoN9wzCAGY0wzSECuZyccNa3Ew+/8XDa2B10L+/4zcz1f/YO2BQy9K/dBHyDhM6Zj6nInkP+6/CW+fyHlO5ozh1NamKzhHbKNd2LiHv3YVDVboQ7CDe48wav5fDAusmbUjZ3Fo5/bASYnrJgPI6PwtMp83mwjCOMwgP4nJlY9s8RIy7p21bSjcjeP7SU+fgRd3TpXP/iPtg3oIArdUEz4mXrRKqtoW4nbfJlE0SKz9sHfxaJLswXw9SpVZTLsNfLHkD1W63CBgAAFALMipDK+JdIl8Nmrd++tcoHYakMl5iwXiUeBPtPJwLQkIkHEFxBWBPbiOleBHPYsCswjt2Jjb/7kj1JzOE822ziVvwsS6q94zxDeu+6Ui4BlzrGvpuMRVYwnx63qGX8mkUtDyU+ZlU="
      
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  #- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=fs7-final-project
  #- mvn clean verify sonar:sonar -Pcoverage -Dsonar.projectKey=fs7-final-project
  #- mvn clean verify sonar:sonar
  - mvn clean test
  #- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=fs7-final-project
