language: java

jdk:
  - openjdk8

addons:
  sonarcloud:
    organization: "fs7-final-project"
    token:
      secure: "Rdn0mlRXP6eSlAPOCYzd+AAD+PYXRJ+bcpvZ6RZJ6SV7s9v0+fuaavVtkR4x6cbn7JOthQSUMbVF0N2POy1AsITv0NE2KUt/NeQetpZyx92qDeeTGR6p8mdDqrKd5u0cpjTnVgqahC+rkiYvMogdxuFjjLVd1gG9xcbD2uMi3KmYA7d4SJAfykeEDR49cAmwTU+6TE8f9qwydOJdijqsjEJzFZKwhcyCHiryy6XrywlFHY4dWHEx5+H8v/70tzGEovmC7HaNWt/Ui8v2IuN9m6QofZNzshwCsPJlK2rMm6fl7hJ0wm9NSugxqI8eE+2Z17IzDRjcMGZ26ghkTyb16WumcOVu2hRkBllephdLkwWahrBTNqDFZNmE8851MAT4+eQBfXuqCIMiYs7IjnsMW/qqmwbiSDjC5P7Jk/j1TFKzfvSizFDxOh5tUdapYqpnGEs0C5JtDsv6u5DSd9ZopXL489A/WHnvVPWY/SwCBLmVeSOB5MA5qg7Y+Dm1+zEG6ATREw+FJ9EAQ+dz+yok71E+jHJSelHI2HZmJSdwSA0Az8ZnJT1Fxui0FhFbNDYS6ImiTmvor7hyJ0BKhidSeBP+M5Ymr0a5f4hRbJzOCoqiIM7zGhDGoUuA9Na1KT88tkbQ3LHXyA9C30h0IzLImiMgBmkJje7EZ+QdiDBAmpk="
      
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  #- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=fs7-final-project
  - mvn clean verify sonar:sonar -Pcoverage -Dsonar.projectKey=fs7-final-project
  #- mvn clean verify sonar:sonar
  #- mvn clean test
  #- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=fs7-final-project
