language: java

jdk:
  - openjdk8

addons:
  sonarcloud:
    organization: "fs7-final-project"
    token:
      secure: "KnJ3/KSChAQXcn31K8NG4C/kKXi9itQiYSR90e30Sf117B5saQDlQ6XBAcTgCdBM8Bil/DKAvYdXaxpCE6sre2MHIlz0ZmISg/azBooDwlwq/t97QLsNdKx+7sDb7RmL7gOnmZltTjDeFVpeAfpgXoFtb+FTCyTM0wx0P83SJsUnXbjrPk6HPFuvq/bbP3PH0v0mqG4nqBp/ccGNN8+8zQg9T6jzxuSboRdOxgjXky9kreJCrplNJyYVd7rFNX+xU7qZmnQAk1HzulgwvTLKTuDcTlsVwOJvZhcrxSB2ZPU/biUbUmHS1VVLf/5hQ6PzPpigHH+N6zMs+z98lEw8SfHTBhv4QfMioqzDIfV09stT5xiEPriXOceiWyYUzESTab+Qy0BKVi68CYn5nXhzW4Q+NY0B3glEChX4/CGjBjB8k/TXqITP58TaXyZAWihtJfpxtx6hQxY7gW32bRQEx51e/6BDGVGcjROWVrTnIA8GOL+RQ2h7+/Eq6OF6NKqV5q0Oa+Fvw22JrjC3zsAcSSNrLPIm4wX3KNQ4RK0pxeGH6U+Nh1ys69iqz9rpH6Layd+XaKN9eABjacwYFhTMoXboKYUv5Pi/YP2i0v8X9UZe4PvODBTKW4FWS56kIK479USZoUkECLZVlOUxiWMcnA4KKKZaQ9a4IUYk1xW+6hU="

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  #- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=fs7-final-project
  #- mvn clean verify sonar:sonar -Pcoverage -Dsonar.projectKey=fs7-final-project
  #- mvn clean verify sonar:sonar
  #- mvn clean test
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=fs7-final-project
